---
  root: true
  extends:
    - airbnb-base/legacy
  env:
    browser: true
    node: true
    amd: true
  rules:
    # Customised whitespace
    max-len:
      - 1
      - 80
      - 2
      -
        ignoreUrls: true
        ignoreComments: false
    indent:
      - 1
      - 2
      -
        SwitchCase: 1
        VariableDeclarator:
          var: 2
          let: 2
          const: 3
        outerIIFEBody: 1
    no-multi-spaces:
      - 1
      -
        exceptions:
          VariableDeclarator: true
    key-spacing:
      - 1
      -
        align: value
    space-before-function-paren:
      - 1
      - never

    # Customised to existing code's style
    semi:
      - 1
      - never

    # You don't need this one when you know your operators
    no-mixed-operators: 0

    # Additional rules
    func-names: 0

    # Disabled for IE8 support
    comma-dangle: 0

    # Airbnb rules that were disabled due to too many conflicts
    # with the existing code style
    vars-on-top: 0
    one-var: 0
    no-use-before-define: 0
